In [92]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [93]:
heart = pd.read_csv('https://raw.githubusercontent.com/robotautas/kursas/master/Machine%20Learning/heart.csv')

In [94]:
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope   
0   63    1   3       145   233    1        0      150      0      2.3      0  \
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [95]:
heart.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [96]:
heart.info

<bound method DataFrame.info of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak   
0     63    1   3       145   233    1        0      150      0      2.3  \
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1    

In [97]:
heart['cp'].unique()

array([3, 2, 1, 0], dtype=int64)

In [98]:
heart['slope'].unique()

array([0, 2, 1], dtype=int64)

In [99]:
heart['ca'].unique()

array([0, 2, 1, 3, 4], dtype=int64)

In [100]:
heart['thal'].unique()

array([1, 2, 3, 0], dtype=int64)

In [101]:
dummies_cp = pd.get_dummies(heart['cp'])
dummies_cp.columns = ['cp0', 'cp1', 'cp2', 'cp3']
dummies_cp = dummies_cp.astype(int)
dummies_slope = pd.get_dummies(heart['slope'])
dummies_slope.columns = ['slope0', 'slope1', 'slope2']
dummies_slope = dummies_slope.astype(int)
dummies_ca = pd.get_dummies(heart['ca'])
dummies_ca.columns = ['ca0', 'ca1', 'ca2', 'ca3', 'ca4']
dummies_ca = dummies_ca.astype(int)
dummies_thal = pd.get_dummies(heart['thal'])
dummies_thal.columns = ['thal0', 'thal1', 'thal2', 'thal3']
dummies_thal = dummies_thal.astype(int)

In [102]:
dummies = pd.concat([dummies_ca, dummies_cp, dummies_slope, dummies_thal], axis=1)
dummies.head()

ca0  ca1  ca2  ca3  ca4  cp0  cp1  cp2  cp3  slope0  slope1  slope2  thal0   
0    1    0    0    0    0    0    0    0    1       1       0       0      0  \
1    1    0    0    0    0    0    0    1    0       1       0       0      0   
2    1    0    0    0    0    0    1    0    0       0       0       1      0   
3    1    0    0    0    0    0    1    0    0       0       0       1      0   
4    1    0    0    0    0    1    0    0    0       0       0       1      0   

   thal1  thal2  thal3  
0      1      0      0  
1      0      1      0  
2      0      1      0  
3      0      1      0  
4      0      1      0

In [103]:
heart.drop(columns = ['ca', 'cp', 'slope', 'thal'], inplace=True)
df = pd.concat([heart, dummies], axis=1)

In [104]:
df.head()

age  sex  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  target   
0   63    1       145   233    1        0      150      0      2.3       1  \
1   37    1       130   250    0        1      187      0      3.5       1   
2   41    0       130   204    0        0      172      0      1.4       1   
3   56    1       120   236    0        1      178      0      0.8       1   
4   57    0       120   354    0        1      163      1      0.6       1   

   ...  cp1  cp2  cp3  slope0  slope1  slope2  thal0  thal1  thal2  thal3  
0  ...    0    0    1       1       0       0      0      1      0      0  
1  ...    0    1    0       1       0       0      0      0      1      0  
2  ...    1    0    0       0       0       1      0      0      1      0  
3  ...    1    0    0       0       0       1      0      0      1      0  
4  ...    0    0    0       0       0       1      0      0      1      0  

[5 rows x 26 columns]

In [105]:
X = df.drop('target', axis=1)
X.head()

age  sex  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  ca0  ...   
0   63    1       145   233    1        0      150      0      2.3    1  ...  \
1   37    1       130   250    0        1      187      0      3.5    1  ...   
2   41    0       130   204    0        0      172      0      1.4    1  ...   
3   56    1       120   236    0        1      178      0      0.8    1  ...   
4   57    0       120   354    0        1      163      1      0.6    1  ...   

   cp1  cp2  cp3  slope0  slope1  slope2  thal0  thal1  thal2  thal3  
0    0    0    1       1       0       0      0      1      0      0  
1    0    1    0       1       0       0      0      0      1      0  
2    1    0    0       0       0       1      0      0      1      0  
3    1    0    0       0       0       1      0      0      1      0  
4    0    0    0       0       0       1      0      0      1      0  

[5 rows x 25 columns]

In [106]:
y = df['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = \
train_test_split(X, y, test_size=0.75, random_state=55)

In [108]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', max_iter=300).fit(X_train, y_train)

In [109]:
model.score(X_train, y_train)

1.0

In [110]:
lr_preds = model.predict(X_test)
from sklearn.metrics import confusion_matrix
lr_cm = confusion_matrix(y_test, lr_preds)
lr_cm

array([[ 73,  33],
       [ 11, 111]], dtype=int64)

In [111]:
from sklearn.linear_model import LogisticRegression
model_newton_cg = LogisticRegression(solver='newton-cg').fit(X_train, y_train)

In [112]:
lr_newton_preds = model_newton_cg.predict(X_test)
from sklearn.metrics import confusion_matrix
lr_newton_cm = confusion_matrix(y_test, lr_newton_preds)
lr_newton_cm

array([[ 73,  33],
       [ 11, 111]], dtype=int64)

In [113]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier().fit(X_train, y_train)
dtc.score(X_test, y_test)

0.7280701754385965

In [114]:
dtc_preds = dtc.predict(X_test)
dtc_cm = confusion_matrix(y_test, dtc_preds)
dtc_cm

array([[ 57,  49],
       [ 13, 109]], dtype=int64)

In [115]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 5000).fit(X_train, y_train)
rfc.score(X_test, y_test)

0.7982456140350878

In [116]:
def optimal_estimators(state, est):
    list_of_dicts = []
    for s in range(state):
        index_value_pairs = {}
        for i in range(est):
            rfc = RandomForestClassifier(n_estimators = i+1, random_state= s+1).fit(X_train, y_train)
            index_value_pairs.update({f'estimators{i+1}':rfc.score(X_test, y_test)})
        list_of_dicts.append(index_value_pairs)
    return list_of_dicts

In [117]:
opt = optimal_estimators(50, 50)

In [118]:
best_values = pd.DataFrame(opt).T
best_values.columns = columns = list(range(1, len(opt)+1))
best_values.head()

1         2         3         4         5         6    
estimators1  0.745614  0.679825  0.697368  0.723684  0.697368  0.750000  \
estimators2  0.732456  0.728070  0.723684  0.745614  0.728070  0.745614   
estimators3  0.754386  0.741228  0.692982  0.750000  0.771930  0.750000   
estimators4  0.785088  0.771930  0.728070  0.780702  0.745614  0.750000   
estimators5  0.771930  0.758772  0.714912  0.758772  0.750000  0.754386   

                   7         8         9         10  ...        41        42   
estimators1  0.732456  0.776316  0.763158  0.710526  ...  0.763158  0.763158  \
estimators2  0.758772  0.807018  0.763158  0.701754  ...  0.754386  0.807018   
estimators3  0.754386  0.767544  0.763158  0.736842  ...  0.780702  0.771930   
estimators4  0.771930  0.771930  0.771930  0.741228  ...  0.767544  0.780702   
estimators5  0.776316  0.750000  0.771930  0.754386  ...  0.789474  0.771930   

                   43        44        45        46        47        48   
estimators1  0.728070  0.750000  0.649123  0.758772  0.723684  0.754386  \
estimators2  0.771930  0.719298  0.653509  0.767544  0.758772  0.706140   
estimators3  0.763158  0.736842  0.714912  0.771930  0.758772  0.771930   
estimators4  0.785088  0.745614  0.741228  0.793860  0.789474  0.763158   
estimators5  0.776316  0.750000  0.758772  0.780702  0.780702  0.767544   

                   49        50  
estimators1  0.776316  0.750000  
estimators2  0.741228  0.754386  
estimators3  0.802632  0.767544  
estimators4  0.802632  0.776316  
estimators5  0.807018  0.754386  

[5 rows x 50 columns]

In [119]:
best_values.max().idxmax()

1

In [120]:
best_values.idxmax()[35]

'estimators40'

In [121]:
from sklearn.ensemble import RandomForestClassifier
rfc_optimized = RandomForestClassifier(n_estimators = 11, random_state=35).fit(X_train, y_train)
rfc_optimized.score(X_test, y_test)

0.7192982456140351

In [122]:
rfc_preds = rfc_optimized.predict(X_test)
rfc_cm = confusion_matrix(y_test, rfc_preds)
rfc_cm

array([[ 61,  45],
       [ 19, 103]], dtype=int64)

In [123]:
y_test.value_counts()

target
1    122
0    106
Name: count, dtype: int64

In [124]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X)
scaled_features = scaler.transform(X)
scaled_features[:4]

array([[ 0.9521966 ,  0.68100522,  0.76395577, -0.25633371,  2.394438  ,
        -1.00583187,  0.01544279, -0.69663055,  1.08733806,  0.85523597,
        -0.52259855, -0.37867694, -0.26584089, -0.12953194, -0.94538352,
        -0.44455422, -0.63464776,  3.4891135 ,  3.66450153, -0.92676626,
        -0.93914194, -0.08151391,  3.97911213, -1.10076284, -0.79311554],
       [-1.91531289,  0.68100522, -0.09273778,  0.07219949, -0.41763453,
         0.89896224,  1.63347147, -0.69663055,  2.12257273,  0.85523597,
        -0.52259855, -0.37867694, -0.26584089, -0.12953194, -0.94538352,
        -0.44455422,  1.57567719, -0.28660575,  3.66450153, -0.92676626,
        -0.93914194, -0.08151391, -0.25131234,  0.9084609 , -0.79311554],
       [-1.47415758, -1.46841752, -0.09273778, -0.81677269, -0.41763453,
        -1.00583187,  0.97751389, -0.69663055,  0.31091206,  0.85523597,
        -0.52259855, -0.37867694, -0.26584089, -0.12953194, -0.94538352,
         2.24944438, -0.63464776, -0.28660575, -0

In [125]:
features = pd.DataFrame(scaled_features, columns=X.columns)

In [126]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   trestbps  303 non-null    float64
 3   chol      303 non-null    float64
 4   fbs       303 non-null    float64
 5   restecg   303 non-null    float64
 6   thalach   303 non-null    float64
 7   exang     303 non-null    float64
 8   oldpeak   303 non-null    float64
 9   ca0       303 non-null    float64
 10  ca1       303 non-null    float64
 11  ca2       303 non-null    float64
 12  ca3       303 non-null    float64
 13  ca4       303 non-null    float64
 14  cp0       303 non-null    float64
 15  cp1       303 non-null    float64
 16  cp2       303 non-null    float64
 17  cp3       303 non-null    float64
 18  slope0    303 non-null    float64
 19  slope1    303 non-null    float64
 20  slope2    303 non-null    float6

In [127]:
from sklearn.neighbors import KNeighborsClassifier
XX_train, XX_test, yy_train, yy_test = \
train_test_split(features, y, test_size=0.4, random_state=42)
heart_knc = KNeighborsClassifier(n_neighbors = 103).fit(XX_train, yy_train)
heart_knc.score(XX_test, yy_test)

0.8934426229508197

In [128]:
knc_preds = heart_knc.predict(XX_test)
knc_cm = confusion_matrix(yy_test, knc_preds)
knc_cm

array([[42, 10],
       [ 3, 67]], dtype=int64)

In [129]:
def find_optimal(neighbors):
    score_dict = {}
    for i in range(neighbors):
        knc_optimized = KNeighborsClassifier(n_neighbors = i+1).fit(XX_train, yy_train)
        score_dict.update({i+1:knc_optimized.score(XX_test, yy_test)})
    return score_dict

In [130]:
neighbors_dict = find_optimal(132)
max_sample = max(neighbors_dict, key=neighbors_dict.get)
max_sample

101

In [131]:
neighbors_dict[101]

0.8934426229508197

In [132]:
indexes = []
for k, v in neighbors_dict.items():
    if v == 0.8934426229508197:
        indexes.append(k)
indexes

[101, 103]