In [7]:
import numpy as np

In [1]:
#1
vektorius = np.arange(1, 10)
print(vektorius)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [2]:
#2
vektorius = [0] * 10
print(vektorius)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [3]:
#3
vektorius = [1] * 10
print(vektorius)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [4]:
#4
vektorius = [4] * 10
print(vektorius)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


In [5]:
#5
vektorius = list(range(0, 101, 2))
print(vektorius)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [8]:
#6
matrica = np.arange(1, 26).reshape(5, 5)
print(matrica)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
